server:
  port: 8989
  servlet:
    context-path: /case
spring:
  application:
    name: user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vueboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true